### PR TITLE
Run tests against pull requests

### PR DESCRIPTION
**Pull request by lesserwhirls**
Run `mvn verify` against all pull requests using AdoptOpenJDK 8, 11, and 15. If one or more tests fail, upload the test report directory and attach it as an artifact to the github action.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Example GitHub Action run:

https://github.com/Unidata/geoapi-netcdf-java/actions/runs/657611835

@desruisseaux - can you think of any reason why we would not want to enable this check at this stage?

**Comment by desruisseaux** [comment]
No reason I'm aware of. I'm just unfamiliar with GitHub workflow (yet another technology too fast for me to catch up).

**Comment by lesserwhirls** [comment]
It's similar to Jenkins or Travis, but built-in to GitHub. I'll go ahead and merge this in so that future PRs will get tested as work progresses.

**Comment by desruisseaux** [comment]
Thanks!

**Pull request merged**
