### PR TITLE
GeoAPI wrappers initial copy (edited)

### PR DESCRIPTION
**Pull request by desruisseaux**
This initial set of classes is built against GeoAPI 3.0.1 and netCDF 4.

### CODE REVIEW

**Comment by desruisseaux** [comment]
I just realized that I forgot to update the copyright header. I will do that in next commit.

**Comment by desruisseaux** [comment]
What about the following copyright header? I copied it from `NetcdfDataset.java` with the following clhanges:

* Removed the years after "Copyright" because they tend to not be kept up-to-date.
* Removed (for now) the paragraph saying "Portions of this software were developed by the Unidata Program at the University Corporation for Atmospheric Research" because it is not yet the case.

Would it be okay?

```
/*
 * Copyright University Corporation for Atmospheric Research/Unidata
 *
 *   Access and use of this software shall impose the following obligations
 *   and understandings on the user. The user is granted the right, without
 *   any fee or cost, to use, copy, modify, alter, enhance and distribute
 *   this software, and any derivative works thereof, and its supporting
 *   documentation for any purpose whatsoever, provided that this entire
 *   notice appears in all copies of the software, derivative works and
 *   supporting documentation.  Further, UCAR requests that the user credit
 *   UCAR/Unidata in any publications that result from the use of this
 *   software or in any product that includes this software. The names UCAR
 *   and/or Unidata, however, may not be used in any advertising or publicity
 *   to endorse or promote any products or commercial entity unless specific
 *   written permission is obtained from UCAR/Unidata. The user also
 *   understands that UCAR/Unidata is not obligated to provide the user with
 *   any support, consulting, training or assistance of any kind with regard
 *   to the use, operation and performance of this software nor to provide
 *   the user with any updates, revisions, new versions or "bug fixes."
 *
 *   THIS SOFTWARE IS PROVIDED BY UCAR/UNIDATA "AS IS" AND ANY EXPRESS OR
 *   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL UCAR/UNIDATA BE LIABLE FOR ANY SPECIAL,
 *   INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
 *   FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 *   NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
 *   WITH THE ACCESS, USE OR PERFORMANCE OF THIS SOFTWARE.
 */
```

**Comment by desruisseaux** [comment]
I'm moving above questions in separated issues, and changed my mind about license header by reverting the proposed changes: discussion on https://github.com/Unidata/geoapi-netcdf-java/issues/2. I will squash the commits later today in order to have only one single, complete and functional commit.

**Comment by desruisseaux** [comment]
Hello @lesserwhirls

A report on the code sprint will be presented at the [OGC meeting in one week](https://portal.ogc.org/meet/?p=meeting&mid=84). Do you think this merge request could be merged for that meeting? Or let me know if there is any thing to change. The intent is to avoid having an empty repository if some peoples want to take a look.

**Comment by lesserwhirls** [comment]
Yes, for sure! I missed the PR getting switched over from Draft to ready for review, and I apologize for that. I'll go ahead and merge this in and we can move to the next steps. Thank you @desruisseaux!

**Pull request merged**
